<a href="https://colab.research.google.com/github/vikram9540/AirBnB_PowerBI_Visualization_Dashboard/blob/main/Copy_of_AirBnB_Project_Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
listNO=pd.read_csv('/content/drive/MyDrive/Project/Power BI/AirBnb Project/listings NO (1).csv')
listCH=pd.read_csv('/content/drive/MyDrive/Project/Power BI/AirBnb Project/listings CH (1).csv')

In [ ]:
listCH.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.78790,-87.58780,Private room,125.0,3,250,2024-10-14,2.02,1,343,16,R17000015609
1,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,West Town,41.90166,-87.68021,Entire home/apt,81.0,2,569,2025-02-09,2.98,1,275,53,R24000114046
2,10945,The Biddle House (#1),33004,At Home Inn,NaN,Lincoln Park,41.91196,-87.63981,Entire home/apt,187.0,4,117,2025-01-02,0.88,6,260,34,2209984
3,28749,Quirky Bucktown Loft w/ Parking No Parties,27506,Lauri,NaN,Logan Square,41.91955,-87.70069,Entire home/apt,196.0,2,244,2025-03-09,1.40,1,55,47,R24000113825
4,71930,"Rest, Relax and Explore",334241,Michael And Veronica,NaN,West Town,41.89615,-87.67934,Private room,76.0,3,129,2024-11-26,0.77,1,0,19,R23000108832

In [ ]:
listNO.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,19091,Fully Furnished Cozy Apartment,72880,John,NaN,Leonidas,29.96100,-90.11950,Entire home/apt,61.0,30,503,2023-11-06,2.78,1,329,0,"22-RSTR-14107, 22-OSTR-14105"
1,71624,Ravenwood Manor (Historic Bywater),367223,Susan,NaN,Bywater,29.96153,-90.04364,Entire home/apt,167.0,30,313,2025-02-02,1.83,1,342,15,"21-RSTR-18609, 22-OSTR-20720"
2,74498,Maison Marais 1,391462,Georgia,NaN,St. Roch,29.96986,-90.05172,Entire home/apt,150.0,3,649,2025-02-23,3.82,3,208,35,23-XSTR-13082
3,79536,FeelAtHomeInNewOrleans-PrivateApt,428362,Miriam,NaN,Seventh Ward,29.97803,-90.07450,Entire home/apt,179.0,3,768,2025-03-01,4.56,1,0,59,"23-NSTR-15067, 24-OSTR-20882"
4,79609,Bywater's Original & Finest,428909,Stephen,NaN,St. Claude,29.96448,-90.03667,Entire home/apt,136.0,30,505,2024-11-14,2.97,1,341,13,"23-ISTR-02823, 23-OSTR-02823"

In [ ]:
listCH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8748 entries, 0 to 8747
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              8748 non-null   int64
 1   name                            8748 non-null   object
 2   host_id                         8748 non-null   int64
 3   host_name                       8748 non-null   object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   8748 non-null   object
 6   latitude                        8748 non-null   float64
 7   longitude                       8748 non-null   float64
 8   room_type                       8748 non-null   object
 9   price                           7718 non-null   float64
 10  minimum_nights                  8748 non-null   int64
 11  number_of_reviews               8748 non-null   int64
 12  last_review                     6870 non-null   object
 13  reviews_per_month               6870 non-null   float64
 14  calculated_host_listings_count  8748 non-null   int64
 15  availability_365                8748 non-null   int64
 16  number_of_reviews_ltm           8748 non-null   int64
 17  license                         6845 non-null   object
dtypes: float64(5), int64(7), object(6)
memory usage: 1.2+ MB

In [ ]:
listNO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7842 entries, 0 to 7841
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7842 non-null   int64
 1   name                            7842 non-null   object
 2   host_id                         7842 non-null   int64
 3   host_name                       7829 non-null   object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   7842 non-null   object
 6   latitude                        7842 non-null   float64
 7   longitude                       7842 non-null   float64
 8   room_type                       7842 non-null   object
 9   price                           6640 non-null   float64
 10  minimum_nights                  7842 non-null   int64
 11  number_of_reviews               7842 non-null   int64
 12  last_review                     6514 non-null   object
 13  reviews_per_month               6514 non-null   float64
 14  calculated_host_listings_count  7842 non-null   int64
 15  availability_365                7842 non-null   int64
 16  number_of_reviews_ltm           7842 non-null   int64
 17  license                         6493 non-null   object
dtypes: float64(5), int64(7), object(6)
memory usage: 1.1+ MB

In [ ]:
listCH.drop('neighbourhood_group', axis=1, inplace=True)

In [ ]:
listNO.drop('neighbourhood_group', axis=1, inplace=True)

In [ ]:
listCH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8748 entries, 0 to 8747
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              8748 non-null   int64
 1   name                            8748 non-null   object
 2   host_id                         8748 non-null   int64
 3   host_name                       8748 non-null   object
 4   neighbourhood                   8748 non-null   object
 5   latitude                        8748 non-null   float64
 6   longitude                       8748 non-null   float64
 7   room_type                       8748 non-null   object
 8   price                           7718 non-null   float64
 9   minimum_nights                  8748 non-null   int64
 10  number_of_reviews               8748 non-null   int64
 11  last_review                     6870 non-null   object
 12  reviews_per_month               6870 non-null   float64
 13  calculated_host_listings_count  8748 non-null   int64
 14  availability_365                8748 non-null   int64
 15  number_of_reviews_ltm           8748 non-null   int64
 16  license                         6845 non-null   object
dtypes: float64(4), int64(7), object(6)
memory usage: 1.1+ MB

In [ ]:
listNO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7842 entries, 0 to 7841
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7842 non-null   int64
 1   name                            7842 non-null   object
 2   host_id                         7842 non-null   int64
 3   host_name                       7829 non-null   object
 4   neighbourhood                   7842 non-null   object
 5   latitude                        7842 non-null   float64
 6   longitude                       7842 non-null   float64
 7   room_type                       7842 non-null   object
 8   price                           6640 non-null   float64
 9   minimum_nights                  7842 non-null   int64
 10  number_of_reviews               7842 non-null   int64
 11  last_review                     6514 non-null   object
 12  reviews_per_month               6514 non-null   float64
 13  calculated_host_listings_count  7842 non-null   int64
 14  availability_365                7842 non-null   int64
 15  number_of_reviews_ltm           7842 non-null   int64
 16  license                         6493 non-null   object
dtypes: float64(4), int64(7), object(6)
memory usage: 1.0+ MB

In [ ]:
listNO.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                           13
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                             1202
minimum_nights                       0
number_of_reviews                    0
last_review                       1328
reviews_per_month                 1328
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           1349
dtype: int64

In [ ]:
listCH.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                             1030
minimum_nights                       0
number_of_reviews                    0
last_review                       1878
reviews_per_month                 1878
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           1903
dtype: int64

In [ ]:
# changing the datatype of date column
listCH['last_review'] = pd.to_datetime(listCH['last_review'])
listNO['last_review'] = pd.to_datetime(listNO['last_review'])

In [ ]:
listCH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8748 entries, 0 to 8747
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              8748 non-null   int64
 1   name                            8748 non-null   object
 2   host_id                         8748 non-null   int64
 3   host_name                       8748 non-null   object
 4   neighbourhood                   8748 non-null   object
 5   latitude                        8748 non-null   float64
 6   longitude                       8748 non-null   float64
 7   room_type                       8748 non-null   object
 8   price                           7718 non-null   float64
 9   minimum_nights                  8748 non-null   int64
 10  number_of_reviews               8748 non-null   int64
 11  last_review                     6870 non-null   datetime64[ns]
 12  reviews_per_month               6870 non-null   float64
 13  calculated_host_listings_count  8748 non-null   int64
 14  availability_365                8748 non-null   int64
 15  number_of_reviews_ltm           8748 non-null   int64
 16  license                         6845 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(7), object(5)
memory usage: 1.1+ MB

In [ ]:
listNO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7842 entries, 0 to 7841
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7842 non-null   int64
 1   name                            7842 non-null   object
 2   host_id                         7842 non-null   int64
 3   host_name                       7829 non-null   object
 4   neighbourhood                   7842 non-null   object
 5   latitude                        7842 non-null   float64
 6   longitude                       7842 non-null   float64
 7   room_type                       7842 non-null   object
 8   price                           6640 non-null   float64
 9   minimum_nights                  7842 non-null   int64
 10  number_of_reviews               7842 non-null   int64
 11  last_review                     6514 non-null   datetime64[ns]
 12  reviews_per_month               6514 non-null   float64
 13  calculated_host_listings_count  7842 non-null   int64
 14  availability_365                7842 non-null   int64
 15  number_of_reviews_ltm           7842 non-null   int64
 16  license                         6493 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(7), object(5)
memory usage: 1.0+ MB

In [ ]:
#filling na in price columns
listCH['price'].fillna(listCH['price'].mode()[0], inplace=True)
listNO['price'].fillna(listNO['price'].mode()[0], inplace=True)

<ipython-input-47-f172eedb9dfb>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  listCH['price'].fillna(listCH['price'].mode()[0], inplace=True)
<ipython-input-47-f172eedb9dfb>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  listNO['price'].fillna(listNO['price'].mode()[0], inplace=True)

In [ ]:
listCH.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                                0
minimum_nights                       0
number_of_reviews                    0
last_review                       1878
reviews_per_month                 1878
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           1903
dtype: int64

In [ ]:
listNO.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                           13
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                                0
minimum_nights                       0
number_of_reviews                    0
last_review                       1328
reviews_per_month                 1328
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           1349
dtype: int64

In [ ]:
listCH.to_excel('/content/drive/MyDrive/Project/Power BI/AirBnb Project/listings CH (1).csv', index=False)

In [ ]:
listNO.to_excel('/content/drive/MyDrive/Project/Power BI/AirBnb Project/listings NO (1).csv', index=False )